import React, { lazy } from 'react';
import {
  FilesIcon,
  EditorIcon,
  TerminalIcon,
  BrowserIcon,
  GamesIcon,
  SettingsIcon,
  CameraIcon,
  PhotosIcon,
  WeatherIcon,
  ClockIcon,
} from '../icons/AppIcons.js';

export const APP_REGISTRY = {
  files: {
    id: 'files',
    title: 'Files',
    icon: FilesIcon,
    defaultSize: { width: 840, height: 530 },
    singleInstance: false,
    component: lazy(() => import('./files/FilesApp')),
  },
  browser: {
    id: 'browser',
    title: 'Browser',
    icon: BrowserIcon,
    defaultSize: { width: 880, height: 590 },
    singleInstance: false,
    component: lazy(() => import('./browser/BrowserApp')),
  },
  camera: {
    id: 'camera',
    title: 'Camera',
    icon: CameraIcon,
    defaultSize: { width: 680, height: 520 },
    singleInstance: true,
    component: lazy(() => import('./camera/CameraApp')),
  },
  photos: {
    id: 'photos',
    title: 'Photos',
    icon: PhotosIcon,
    defaultSize: { width: 860, height: 560 },
    singleInstance: false,
    component: lazy(() => import('./photos/PhotosApp')),
  },
  weather: {
    id: 'weather',
    title: 'Weather',
    icon: WeatherIcon,
    defaultSize: { width: 620, height: 560 },
    singleInstance: false,
    component: lazy(() => import('./weather/WeatherApp')),
  },
  clock: {
    id: 'clock',
    title: 'Clock',
    icon: ClockIcon,
    defaultSize: { width: 660, height: 490 },
    singleInstance: false,
    component: lazy(() => import('./clock/ClockApp')),
  },
  editor: {
    id: 'editor',
    title: 'Text Editor',
    icon: EditorIcon,
    defaultSize: { width: 860, height: 560 },
    singleInstance: false,
    component: lazy(() => import('./editor/TextEditor')),
  },
  terminal: {
    id: 'terminal',
    title: 'Terminal',
    icon: TerminalIcon,
    defaultSize: { width: 720, height: 460 },
    singleInstance: false,
    component: lazy(() => import('./terminal/TerminalApp')),
  },
  games: {
    id: 'games',
    title: 'Games',
    icon: GamesIcon,
    defaultSize: { width: 740, height: 500 },
    singleInstance: false,
    component: lazy(() => import('./placeholder/ComingSoon')),
  },
  settings: {
    id: 'settings',
    title: 'Settings',
    icon: SettingsIcon,
    defaultSize: { width: 780, height: 560 },
    singleInstance: true,
    component: lazy(() => import('./settings/SettingsApp')),
  },
};

export const DOCK_APPS = [
  APP_REGISTRY.files,
  APP_REGISTRY.browser,
  APP_REGISTRY.camera,
  APP_REGISTRY.photos,
  APP_REGISTRY.weather,
  APP_REGISTRY.clock,
  APP_REGISTRY.editor,
  APP_REGISTRY.terminal,
  APP_REGISTRY.games,
  APP_REGISTRY.settings,
];

export const getAppManifest = (appId) => APP_REGISTRY[appId] || null;
